### ISSUE TITLE
Using exceptions instead of return codes

### ISSUE THREAD

**Issue by rkr8** [Svalorzen/cpp-readline#6]
This is just an idea, but wouldn't it be more C++-like to use exceptions instead of return codes? The `Console` class could handle those exceptions and automatically print the error messages.

**Comment by Svalorzen** [comment]
Well, if your custom function throws an exception it still gets propagated. In this way you can both use error codes or exceptions as you see fit.

**Comment by rkr8** [comment]
Ah ok. Thanks for the fast answer!
